version: '3'
services:
  app: &app_base
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app/pognito
    expose:
      - 3000
    depends_on:
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 443:443
      - 80:80

  db:
    image: postgres:16.4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${RDS_PASSWORD}
      POSTGRES_HOST: localhost
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - 6379:6379

  tailwind:
    <<: *app_base
    command: bundle exec rails tailwindcss:watch
    ports: []
    depends_on:
      - app

volumes:
  postgres-data:
    driver: local
