version: '3'
services:
  app: &app_base
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/app/pognito
    expose:
      - 3000
    depends_on:
      - redis

  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 443:443
      - 80:80

  redis:
    image: redis
    ports:
      - 6379:6379

  tailwind:
    <<: *app_base
    command: bundle exec rails tailwindcss:watch
    ports: []
    depends_on:
      - app
