default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV["RDS_USERNAME"] %>
  password: <%= ENV["RDS_PASSWORD"] %>
  host: <%= ENV["RDS_HOSTNAME"] %>
  port: <%= ENV["RDS_PORT"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: webapp_development

test:
  <<: *default
  database: webapp_test

staging:
  <<: *default
  database: <%= ENV["RDS_DB_NAME"] %>

production:
  <<: *default
  database: <%= ENV["RDS_DB_NAME"] %>
