Rails/FindById:
  Description: "Prefer find to find_by_id or find_by(id: id)."
  Enabled: false

Rails/HasAndBelongsToMany:
  Description: Prefer has_many :through to has_and_belongs_to_many.
  Enabled: false
  Include:
    - app/models/**/*.rb

Rails/ReadWriteAttribute:
  Description: This cop checks for the use of the read_attribute method.
  Enabled: false

Rails/UnknownEnv:
  Environments:
    - production
    - staging
    - development
    - test
