RSpec/AnyInstance:
  Description: "Avoid stubbing using `any_instance_of`"
  Enabled: false

RSpec/NestedGroups:
  Description: Checks for nested example groups.
  Enabled: true
  Max: 7

RSpec/MultipleExpectations:
  Description: Checks if examples contain too many `expect` calls.
  Enabled: true
  Max: 5

RSpec/ExampleLength:
  Description: Checks if the length of a test exceeds some maximum value
  Enabled: true
  Max: 10
  CountAsOne: ["array", "hash", "heredoc", "method_call"]

RSpec/MultipleMemoizedHelpers:
  Description: Checks if example groups contain too many `let` and `subject` calls.
  Enabled: true
  AllowSubject: true
  Max: 7

RSpec/ContextWording:
  Description: Checks that `context` docstring starts with an allowed prefix.
  Enabled: true
  Prefixes:
    - when
    - with
    - without
    - for
    - and
    - in
    - as

RSpec/VerifiedDoubles:
  Description: Prefer using verifying doubles over normal doubles.
  Enabled: false
